### PR TITLE
Ok, maybe now the unix and git notes files are in the right place??

### PR DESCRIPTION
**Pull request by Kazzyman**
Many thanks in advance for your "patients", I hope i got it right.

### CODE REVIEW

**Comment by ryansobol** [comment]
This PR is better. But it still contains unnecessary files.

https://github.com/codefellows/sea-w25-uge/pull/29/files

**Comment by Kazzyman** [comment]
oops, i am answering emails out of order, sorry, these new tabs in gmail
.... So, the question is, did I pass?  I have added a new GitHub account
for my own android project and was eventually able to get it pushed up to
the new account "brightquasar" is my other username on GitHub email:
brightquasarsoftware@gmail.com, so I have more to practice with, and it
complicates authentications etc. having two accounts on one PC.

**Comment by Kazzyman** [comment]
I am sorry, but closed #29 is greek to me. Probably only because I am not
even a student there yet?

**Comment by ryansobol** [comment]
Unfortunately, this pull request is not adequate. I closed it so you could try again.

**Comment by Kazzyman** [comment]
I see, thanks for the clarification.  I have paid to attend the next
workshop, perhaps I'll see you there.  I have switched from windows to a
MacBookPro so, I am having to learning to use OSX etc. before I will start
again on gitHub.

**Comment by ryansobol** [comment]
Good idea. OS X is really big and I think it's a really smart of you to learn it will before starting a course with us. Here are a few links that you may find useful. Good luck!

https://www.youtube.com/watch?v=wSPisJXyjso
http://www.atomiclearning.com/mac-os-x-10.10-yosemite-training
http://www.lynda.com/Mac-OS-X-tutorials/Mac-OS-X-Yosemite-Essential-Training/179057-2.html
http://www.lynda.com/Mac-OS-X-tutorials/Mac-OS-X-Yosemite-New-Features/181883-2.html

**Pull request closed without merging**
