### PR TITLE
Notes

### PR DESCRIPTION
**Pull request by Kazzyman**

### CODE REVIEW

**Comment by ryansobol** [comment]
Please review this pull request more carefully. It's missing a `unix_notes.txt` file (placed in the correct directory) yet contains a bunch of unnecessary files.

**Comment by Kazzyman** [comment]
I will read the pdf book from the Git site today, and will do it all over.

**Comment by Kazzyman** [comment]
Hi Ryan;

Thanks for giving me this opportunity to try this on my own.  I seem to
have no issues with the assignment until I get to the last two steps.
Before I even try to comprehend the details of the last step (the pull
request), I first have to get past an issue I am having on step 12. "Push
the branch to the origin remote on GitHub.  I am attaching a .txt file
which contains all the details of the issue and all the steps which lead me
there.  I am sure that if I can get you to look it over, you will be able
to teach me something new, fun, and useful.

Many thanks in advance.

Kazzyman

On Wed, Mar 4, 2015 at 1:33 PM, Ryan Sobol <notifications@github.com> wrote:

> Closed #27 <https://github.com/codefellows/sea-w25-uge/pull/27>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codefellows/sea-w25-uge/pull/27#event-246341798>.
>

Assignment:   13 steps:

1. create a fork of this repo (the github remote repo : sea-w25-uge.git), done.

2. clone the fork to your computer. ( this step assumes that one has already created a dir on his computer with a .git file in it??). And; so what we need for this step is the git command to accomplish the task of "cloning" the repo on GitHub.  So:

      git clone https://github.com/Kazzyman/sea-w25-uge.git

    ... that seems to complete step #2.

3. create a new branch called notes. (I must assume that this only refers to the repo on my computer??)  So; the normal command: "git branch notes" fails at this point for some reason having to do with the cloned files not yet being tracked or commited?? So; I run the command: "git add ." which seemed to work fine; then the command: "git commit ..." ... specifically as below ...

   git commit -m "this should only commit the cloned files"

And; that seemed to work fine.  SO THEN; I retry the command: "git branch notes" and now it works just fine.

4. checkout the branch "notes"
         .... and the command: "git checkout notes" seemed to work fine.

5.  create a dir with the same name as your github account, easy.  Done.

6, 7, 8, 9.  add the two "notes" files to the dir created in step 5. Easy/done.

10.  add these untracked files to the staging area.  So; "git add ." does that trick.

11.  commit the changes.  OK, so, the command:
    git commit -a -m "this commits two files, unix and git notes"  works fine.  Done.

12.  push the branch to the origin remote on GitHub.
  So; it seems that this ought to be a very common sort of push, providing that I understand the meaning of "origin remote" to mean the GitHub repo which I created by forking the school's GitHub repo??  If I go look at the browser at my github account it is Kazzyman/sea-s25-uge, and, it says that it was forked from codefellows/sea-w25-uge.  The site has a drop-down which shows that while it is currently on the master branch, there is another branch there also called "notes".  I believe I created that notes branch there (on the remote) some time ago and do not recall now how it all whent down.  ASSUME: that as long as the contents of the remote "notes" branch is ""compatible"" with the new local "notes" branch all should be ready to sync them up with a push???

So; I go ahead and just try a simple "git push origin notes" but that fails:
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
- - - - - - - - - - - - - - - - - - - - - - - - - - - -

So; I try an even simpler: "git push notes"  which also fails but offers a fix that looks like it may be just what I need, so, I go ahead and try:

     git push --set-upstream notes notes

And then retry the "git push notes" command, but it still fails ::

   fatal: 'notes' does not appear to be a git repository
   fatal: Could not read from remote repository.

   Please make sure you have the correct access rights
   and the repository exists.

And; I am kinda stuck here.

**Comment by Kazzyman** [comment]
Well, now this is interesting (I have continued to work on this thing), and
not I get:

rickw_000@RICKS-I7 ~/0_git_folder (notes)
$ git push upstream notes
remote: Permission to codefellows/sea-w25-uge.git denied to Kazzyman.
fatal: unable to access 'https://github.com/codefellows/sea-w25-uge.git/':
The requested URL returned error: 403

rickw_000@RICKS-I7 ~/0_git_folder (notes)
$


Please help

**Comment by ryansobol** [comment]
Hi Rick,

The purpose of the test out assignment is to demonstrate *on your own* that you've already mastered a basic Git workflow. To be completely honest, I can tell you're close but are missing some key concepts.

The purpose of the workshop is to help you master a basic Git workflow so you're prepared for your follow-up course at Code Fellows. If you're struggling with this now, imagine how difficult the follow-up course will be. I hope this makes sense.

The only hint I can give you now is https://help.github.com/categories/managing-remotes/. If you need more hints, come to the next workshop.

**Comment by ryansobol** [comment]
Taking a closer look at your pull request, I see you're very close. However, the PR is missing the `unix_notes.txt` file and has a bunch of unnecessary files.

https://github.com/codefellows/sea-w25-uge/pull/27/files

Try cleaning this up and resubmiting.

**Comment by Kazzyman** [comment]
Yes; I too worry that I may regret missing the workshop on git.  Still
thinking about what i should do though, I am now very interested in swift
and apple iOS after having seen the apple 2014 WWDC videos.

**Pull request closed without merging**
